### PR TITLE
Fix #16: Handle plugins without pom.xml in hpi.

### LINKED ISSUE #16: Fix for plugins created with gradle
Local Directory Repository fails for plugins created with gradle.
Known plugins:
* Pathignore Plugin: http://updates.jenkins-ci.org/download/plugins/pathignore/0.6/pathignore.hpi
* Ivy Plugin: http://updates.jenkins-ci.org/download/plugins/job-dsl/1.45/job-dsl.hpi
* Job-DSL Plugin: http://updates.jenkins-ci.org/download/plugins/ivy/1.26/ivy.hpi

It is caused by:
* ~~no "Extension-Name" in MANIFEST.MF~~
** #22 fixed this issue by using Short-Name.
* no "maven" folder in META-INF

### PR DESCRIPTION
**Pull request by ikedam**
#16
Some plugins (especially plugins build with gradle) doesn't contain pom.xml.
This change allows those plugins (backend-update-center2 originally allows plugins without pom.xml)

### CODE REVIEW

File: src/main/java/org/jvnet/hudson/update_center/LocalHPI.java [hunk 1]
```diff
@@ -73,21 +73,43 @@ public File resolve() throws IOException
...
+            }
+            if (in != null)
+            {
+                in.close();
+            }
+            if (jar != null)
+            {
+                jar.close();
+            }
+        }
```
Comment (ikedam) [inline src/main/java/org/jvnet/hudson/update_center/LocalHPI.java]: Indentation changes.
It may be easy to review with https://github.com/ikedam/backend-update-center2/pull/23/files?w=1

**Comment by ikedam** [comment]
@olivergondza Would you review this change?

**Comment by olivergondza** [comment]
I reproduced the same problem and the fix looks good to me.

**Comment by patrickjmccarty** [comment]
This patch fixed my problems with a handful of plugins that previously caused failure. Thanks!

**Comment by ikedam** [comment]
Thanks for review!
